; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[env]
framework = arduino
platform_packages  =
    framework-arduino-avr @ https://github.com/waflores/ArduinoCore-avr.git#will/add_platformio

[env:uno]
platform = atmelavr
board = uno

[env:teensy41]
platform = teensy
board = teensy41

[env:nanoatmega168]
platform = atmelavr
board = nanoatmega168

[platformio]
description = Cross Platform Arduino I2C Interface
