; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[env]
framework = arduino
platform_packages  =
    framework-arduino-avr @ https://github.com/waflores/ArduinoCore-avr.git#will/add_platformio

[env:mega2560]
platform = atmelavr
board = megaatmega2560
build_flags =
  -DTELEMETRIX_MAX_COMMAND_LENGTH=127
  -DTWI_BUFFER_LENGTH=127
  -DARDUINO_WIRE_TX_BUFFER_LENGTH=127
  -DARDUINO_WIRE_RX_BUFFER_LENGTH=127
  -DTELEMETRIX_I2C_REPORT_BUFFER_SIZE=127

[env:teensy40]
platform = teensy
board = teensy40
build_flags =
  -DTELEMETRIX_MAX_COMMAND_LENGTH=127
  -DARDUINO_WIRE_TX_BUFFER_LENGTH=127
  -DARDUINO_WIRE_RX_BUFFER_LENGTH=127
  -DTELEMETRIX_I2C_REPORT_BUFFER_SIZE=127

[env:nanoatmega168]
platform = atmelavr
board = nanoatmega168
build_flags =
  -DTELEMETRIX_MAX_COMMAND_LENGTH=64
  -DTWI_BUFFER_LENGTH=64
  -DARDUINO_WIRE_TX_BUFFER_LENGTH=64
  -DARDUINO_WIRE_RX_BUFFER_LENGTH=64

[platformio]
description = Cross Platform Arduino I2C Interface
